run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xchainwatcher_5050__202608110852/inference_mlpbased-comparison-xchainwatcher-5050_202608110857
  run_datetime: '2026-08-11T08:57:09'
  checkpoint_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_xchainwatcher_5050__202608110852/models
dataset:
  type: single
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/_dataset_test_xchainwatcher_5050
  stats:
    total_samples: 365
    normal_samples: 281
    anomaly_samples: 84
    anomaly_ratio: 0.2301
    bridges:
    - name: nomad
      num_samples: 364
      normal_samples: 281
      anomaly_samples: 83
      anomaly_ratio: 0.228
      bridge_ratio: 0.9973
    - name: ronin1
      num_samples: 1
      normal_samples: 0
      anomaly_samples: 1
      anomaly_ratio: 1.0
      bridge_ratio: 0.0027
params:
  act: relu
  att_drop: 0.0
  dropout: 0.5
  first_layer_channels: 128
  hidden_channels: 64
  input_drop: 0.0
  n_fp_layers: 2
  n_mlp_layers: 2
  out_channels: 2
  pooling: mean
  residual: false
  rm_semantic_fusion: true
