run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_nomadonly__202608071555/inference_deepsad-comparison-nomadonly_202608071611
  run_datetime: '2026-08-07T16:11:36'
  checkpoint_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.002_nosf_es15_ts0_deepsad_comparison_nomadonly__202608071555/models
dataset:
  type: cctx
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/cctx-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/_dataset_test_nomadonly
  stats:
    total_samples: 47
    normal_samples: 47
    anomaly_samples: 0
    anomaly_ratio: 0.0
    bridges:
    - name: nomad
      num_samples: 47
      normal_samples: 47
      anomaly_samples: 0
      anomaly_ratio: 0.0
      bridge_ratio: 1.0
params:
  act: relu
  att_drop: 0.0
  dropout: 0.5
  first_layer_channels: 128
  hidden_channels: 64
  input_drop: 0.0
  n_fp_layers: 2
  n_mlp_layers: 2
  pooling: mean
  rep_dim: 64
  residual: false
  rm_semantic_fusion: true
