run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/single-mlpbased-final-eval-tuningdme-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_dme0.0665_nosf_es15_mlpbased_tuningdme__202608101732
  run_datetime: '2026-08-10T17:32:48'
params:
  act: relu
  att_drop: 0.0
  augment_factor: 0
  dme_threshold: 0.0665
  dropout: 0.5
  early_stopping: 15
  first_layer_channels: 128
  gpu: cpu
  hidden_channels: 64
  input_drop: 0.0
  k_folds: 5
  learning_rate: 0.005
  n_fp_layers: 2
  n_mlp_layers: 2
  num_epochs: 100
  num_workers: 0
  pooling: mean
  random_seed: 42
  residual: false
  rm_semantic_fusion: true
  test_split: 0.15
dataset:
  type: single
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/single-mlpbased-final-eval-tuningdme-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/_dataset
  stats:
    total_samples: 1152
    normal_samples: 920
    anomaly_samples: 232
    anomaly_ratio: 0.2014
    bridges:
    - name: nomad
      num_samples: 730
      normal_samples: 563
      anomaly_samples: 167
      anomaly_ratio: 0.2288
      bridge_ratio: 0.6337
    - name: polynetwork
      num_samples: 206
      normal_samples: 206
      anomaly_samples: 0
      anomaly_ratio: 0.0
      bridge_ratio: 0.1788
    - name: omnibridge
      num_samples: 85
      normal_samples: 85
      anomaly_samples: 0
      anomaly_ratio: 0.0
      bridge_ratio: 0.0738
    - name: ronin
      num_samples: 56
      normal_samples: 55
      anomaly_samples: 1
      anomaly_ratio: 0.0179
      bridge_ratio: 0.0486
    - name: qubit
      num_samples: 16
      normal_samples: 0
      anomaly_samples: 16
      anomaly_ratio: 1.0
      bridge_ratio: 0.0139
    - name: thorchain2
      num_samples: 15
      normal_samples: 0
      anomaly_samples: 15
      anomaly_ratio: 1.0
      bridge_ratio: 0.013
    - name: harmony
      num_samples: 12
      normal_samples: 0
      anomaly_samples: 12
      anomaly_ratio: 1.0
      bridge_ratio: 0.0104
    - name: xbridge
      num_samples: 9
      normal_samples: 3
      anomaly_samples: 6
      anomaly_ratio: 0.6667
      bridge_ratio: 0.0078
    - name: thorchain3
      num_samples: 8
      normal_samples: 2
      anomaly_samples: 6
      anomaly_ratio: 0.75
      bridge_ratio: 0.0069
    - name: thorchain
      num_samples: 6
      normal_samples: 0
      anomaly_samples: 6
      anomaly_ratio: 1.0
      bridge_ratio: 0.0052
    - name: hypr
      num_samples: 5
      normal_samples: 4
      anomaly_samples: 1
      anomaly_ratio: 0.2
      bridge_ratio: 0.0043
    - name: ronin1
      num_samples: 2
      normal_samples: 0
      anomaly_samples: 2
      anomaly_ratio: 1.0
      bridge_ratio: 0.0017
    - name: meterio
      num_samples: 2
      normal_samples: 2
      anomaly_samples: 0
      anomaly_ratio: 0.0
      bridge_ratio: 0.0017
dme:
  dme_threshold: 0.0665
  reported_metapaths: 1267
