run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/20260716-single-internaltx-comparison-xchainwatcher-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_fullronin1_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607221016/inference_single-xchainwatcher-ronin1_202607221024
  run_datetime: '2026-07-22T10:24:58'
  checkpoint_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/20260716-single-internaltx-comparison-xchainwatcher-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_fullronin1_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607221016/models
dataset:
  type: single
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/20260716-single-internaltx-comparison-xchainwatcher-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_fullronin1_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607221016/_dataset_test_fullronin1
  stats:
    total_samples: 2
    normal_samples: 0
    anomaly_samples: 2
    anomaly_ratio: 1.0
    bridges:
    - name: ronin1
      num_samples: 2
      normal_samples: 0
      anomaly_samples: 2
      anomaly_ratio: 1.0
      bridge_ratio: 1.0
params:
  act: relu
  att_drop: 0.0
  dropout: 0.5
  first_layer_channels: 128
  hidden_channels: 64
  input_drop: 0.0
  n_fp_layers: 2
  n_mlp_layers: 2
  out_channels: 2
  pooling: mean
  residual: false
  rm_semantic_fusion: true
