run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain3only__202608110929/inference_mlpbased-comparison-thorchain3only_202608110936
  run_datetime: '2026-08-11T09:36:14'
  checkpoint_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_ts0_mlpbased_comparison_thorchain3only__202608110929/models
dataset:
  type: single
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/mlpbased-single-eval-comparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/_dataset_test_thorchain3only
  stats:
    total_samples: 8
    normal_samples: 2
    anomaly_samples: 6
    anomaly_ratio: 0.75
    bridges:
    - name: thorchain3
      num_samples: 8
      normal_samples: 2
      anomaly_samples: 6
      anomaly_ratio: 0.75
      bridge_ratio: 1.0
params:
  act: relu
  att_drop: 0.0
  dropout: 0.5
  first_layer_channels: 128
  hidden_channels: 64
  input_drop: 0.0
  n_fp_layers: 2
  n_mlp_layers: 2
  out_channels: 2
  pooling: mean
  residual: false
  rm_semantic_fusion: true
