run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/20260720-single-internaltx-comparison-xscope-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_50label_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607211204/inference_comparison-xscope-50label_202607211220
  run_datetime: '2026-07-21T12:20:41'
  checkpoint_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/20260720-single-internaltx-comparison-xscope-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_50label_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607211204/models
dataset:
  type: single
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/20260720-single-internaltx-comparison-xscope-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_50label_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607211204/_dataset_test_50label
  stats:
    total_samples: 22
    normal_samples: 1
    anomaly_samples: 21
    anomaly_ratio: 0.9545
    bridges:
    - name: qubit
      num_samples: 8
      normal_samples: 0
      anomaly_samples: 8
      anomaly_ratio: 1.0
      bridge_ratio: 0.3636
    - name: thorchain2
      num_samples: 7
      normal_samples: 0
      anomaly_samples: 7
      anomaly_ratio: 1.0
      bridge_ratio: 0.3182
    - name: thorchain3
      num_samples: 4
      normal_samples: 1
      anomaly_samples: 3
      anomaly_ratio: 0.75
      bridge_ratio: 0.1818
    - name: thorchain
      num_samples: 3
      normal_samples: 0
      anomaly_samples: 3
      anomaly_ratio: 1.0
      bridge_ratio: 0.1364
params:
  act: relu
  att_drop: 0.0
  dropout: 0.5
  first_layer_channels: 128
  hidden_channels: 64
  input_drop: 0.0
  n_fp_layers: 2
  n_mlp_layers: 2
  out_channels: 2
  pooling: mean
  residual: false
  rm_semantic_fusion: true
