run_info:
  out_dir: outputs/20260716-single-internaltx-comparison-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_50_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607171548/inference_xchainwatcher-test-ronin1-nomad-recall_202607171557
  run_datetime: '2026-07-17T15:57:54'
  checkpoint_dir: outputs/20260716-single-internaltx-comparison-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/train_50_epochs100_augment0_lr0.005_nosf_es15_ts0.0_202607171548/models
dataset:
  type: single
  path: outputs/20260716-single-internaltx-comparison-ronin2-omni-nomad-polyn-qubit-harmony-thor123-meter-ronin1/_dataset_test_50
  stats:
    total_samples: 366
    normal_samples: 365
    anomaly_samples: 1
    anomaly_ratio: 0.0027
    bridges:
    - name: nomad
      num_samples: 365
      normal_samples: 365
      anomaly_samples: 0
      anomaly_ratio: 0.0
      bridge_ratio: 0.9973
    - name: ronin1
      num_samples: 1
      normal_samples: 0
      anomaly_samples: 1
      anomaly_ratio: 1.0
      bridge_ratio: 0.0027
params:
  act: relu
  att_drop: 0.0
  dropout: 0.5
  first_layer_channels: 128
  hidden_channels: 64
  input_drop: 0.0
  n_fp_layers: 2
  n_mlp_layers: 2
  out_channels: 2
  pooling: mean
  residual: false
  rm_semantic_fusion: true
