run_info:
  out_dir: outputs/mlpbased-single-eval-gnncomparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_gnncomparison__202608102150/timing_test-timing_202608131053
  run_datetime: '2026-08-13T10:53:10'
  checkpoint_dir: outputs/mlpbased-single-eval-gnncomparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_mlpbased_gnncomparison__202608102150/models
  device: cpu
  fold: 1
  warmup_batches: 2
  repeats: 2
dataset:
  type: single
  path: outputs/mlpbased-single-eval-gnncomparison-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/_dataset
