run_info:
  out_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/deepsad-single-eval-efficiency-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_deepsadbased_comparisongnns__202608100943/timing_deepsad-comparison-xchainwatcher-leakfree_202608131201
  run_datetime: '2026-08-13T12:01:05'
  checkpoint_dir: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/deepsad-single-eval-efficiency-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/train_epochs100_augment0_lr0.005_nosf_es15_deepsadbased_comparisongnns__202608100943/models
  device: cpu
  fold: 1
  warmup_batches: 5
  repeats: 3
dataset:
  type: single
  path: /home/gonca/Documents/GitHub/IST-Thesis/BridgeDefender/outputs/deepsad-single-eval-efficiency-ronin12-omni-nomad-polyn-qubit-harmony-thor123-meter-hypr-xbridge/_dataset
